##!smake

include /usr/include/make/commondefs

CC	= CC
LIBS    = -lglut -lGLU -lGL -lXmu -lXext -lX11 -lm
CFILES  = drip.cpp main.cpp
TARGETS = drip

default		: $(TARGETS)

include $(COMMONRULES)

drip	: $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $(OBJECTS) $(LIBS)

# dependencies
$(OBJECTS)	: Drip.h
