##!smake

include /usr/include/make/commondefs

LIBS    = -lglut -lGLU -lGL -lXmu -lXext -lX11 -lm
CFILES  = board.c game.c gliq.c pick.c score.c trackball.c
TARGETS = gliq

default		: $(TARGETS)

include $(COMMONRULES)

$(TARGETS)	: $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $(OBJECTS) $(LIBS)

# dependencies
trackball.o	: trackball.h
$(OBJECTS)	: gliq.h

